version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      [
        "sh",
        "-c",
        "sleep 10 && alembic upgrade head && uvicorn jarvis.main:app --host 0.0.0.0 --reload",
      ]
    restart: on-failure:25
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/jarvis
      - G_LOG_LEVEL=warning
    env_file:
      - .env.local
    volumes:
      - "./jarvis:/code/jarvis"  
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: "postgres:11-alpine"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=jarvis
    ports:
      - "5432:5432"
    volumes:
      - ./jarvis/postgresql:/var/lib/postgresql/data